block specs
addConstantColorBlocks

	blockMorphBuilder
		addCategory: 'color';
		addReporter: 'random' selector: #colorRandom;
		addReporter: 'black' selector: #colorBlack;
		addReporter: 'gray' selector: #colorGray;
		addReporter: 'white' selector: #colorWhite;
		addReporter: 'red' selector: #colorRed;
		addReporter: 'orange' selector: #colorOrange;
		addReporter: 'brown' selector: #colorBrown;
		addReporter: 'yellow' selector: #colorYellow;
		addReporter: 'green' selector: #colorGreen;
		addReporter: 'lime' selector: #colorLime;
		addReporter: 'turquoise' selector: #colorTurquoise;
		addReporter: 'cyan' selector: #colorCyan;
		addReporter: 'sky' selector: #colorSky;
		addReporter: 'blue' selector: #colorBlue;
		addReporter: 'purple' selector: #colorPurple;
		addReporter: 'magenta' selector: #colorMagenta;
		addReporter: 'pink' selector: #colorPink;
		addSeparator