block specs
constantColorBlocks
	^ #(
		'color'
			('random'				r	colorRandom)
			('black'				r	colorBlack)
			('gray'				r	colorGray)
			('white'				r	colorWhite)
			('red'					r	colorRed)
			('orange'			r	colorOrange)
			('brown'				r	colorBrown)
			('yellow'			r	colorYellow)
			('green'				r	colorGreen)
			('lime'				r	colorLime)
			('turquoise'		r	colorTurquoise)
			('cyan'				r	colorCyan)
			('sky'					r	colorSky)
			('blue'				r	colorBlue)
			('purple'			r	colorPurple)
			('magenta'			r	colorMagenta)
			('pink'				r	colorPink)
			-
	)