block specs
setupBlockCategory

	blockMorphBuilder
		setCategory: 'control' color: (Color h: 41 s: 0.85 v: 0.9);
		setCategory: 'operators' color: (Color h: 93 s: 0.9 v: 0.76);
		setCategory: 'sensing' color: (Color h: 200 s: 0.98 v: 0.86);
		setCategory: 'variables' color: ScratchTheme variableBlockColor;
		setCategory: 'list' color: ScratchTheme listBlockColor;
		setCategory: 'basic' color: (Color h: 225 s: 0.65 v: 0.83);
		setCategory: 'color' color: (Color h: 264 s: 0.62 v: 0.89);
		setCategory: 'edges' color: (Color h: 165 s: 1 v: 0.63);
		setCategory: 'nodes' color: (Color h: 296 s: 0.66 v: 0.85)