private
userClasses
	^ super userClasses, #(
		"id		class"
		(111		GratchProject)
		(112		GratchScript)
		(113		GrEdgesScript)
		(114		GrGraphScript)
		(115		GrNodesScript)
		(116		GrBreedId)
		(117		GrNodes)
		(118		GrEdges)
		(119 	GrDisplay)
		(120 	GrNodesVarDef)
		(121 	GrEdgesVarDef)
		"(122 	GrElementsVarId)"
		(123 	GrGraph)
		(124 	GrGraphVarDef)
		(130 	EventId)
		(131		Variables)
		(132		VarDef)
		(133 	LazyArray)
		(134 	StringArray)
	)