initialization
setupButtons
	buttonBasic := self newButton
		label: 'Basic';
		yourself.
	buttonNodes := self newButton
		label: 'Nodes';
		yourself.
	buttonEdges := self newButton
		label: 'Edges';
		yourself.
	buttonControl := self newButton
		label: 'Control';
		yourself.
	buttonColor := self newButton
		label: 'Color';
		yourself.
	buttonSensing := self newButton
		label: 'Sensing';
		yourself.
	buttonOperators := self newButton
		label: 'Operators';
		yourself.
	buttonVariables := self newButton
		label: 'Variables';
		yourself