*Gratch
initializeScanCode
	"self initializeScanCode."
	ScanCode := Array new: 256.
	ScanCode at: 1 + 0 put: $a asciiValue.
	ScanCode at: 1 + 1 put: $s asciiValue.
	ScanCode at: 1 + 2 put: $d asciiValue.
	ScanCode at: 1 + 3 put: $f asciiValue.
	ScanCode at: 1 + 4 put: $h asciiValue.
	ScanCode at: 1 + 5 put: $g asciiValue.
	ScanCode at: 1 + 6 put: $z asciiValue.
	ScanCode at: 1 + 7 put: $x asciiValue.
	ScanCode at: 1 + 8 put: $c asciiValue.
	ScanCode at: 1 + 9 put: $v asciiValue.
	ScanCode at: 1 + 11 put: $b asciiValue.
	ScanCode at: 1 + 12 put: $q asciiValue.
	ScanCode at: 1 + 13 put: $w asciiValue.
	ScanCode at: 1 + 14 put: $e asciiValue.
	ScanCode at: 1 + 15 put: $r asciiValue.
	ScanCode at: 1 + 16 put: $y asciiValue.
	ScanCode at: 1 + 17 put: $t asciiValue.
	ScanCode at: 1 + 18 put: $1 asciiValue.
	ScanCode at: 1 + 19 put: $2 asciiValue.
	ScanCode at: 1 + 20 put: $3 asciiValue.
	ScanCode at: 1 + 21 put: $4 asciiValue.
	ScanCode at: 1 + 22 put: $6 asciiValue.
	ScanCode at: 1 + 23 put: $5 asciiValue.
	ScanCode at: 1 + 25 put: $9 asciiValue.
	ScanCode at: 1 + 26 put: $7 asciiValue.
	ScanCode at: 1 + 28 put: $8 asciiValue.
	ScanCode at: 1 + 29 put: $0 asciiValue.
	ScanCode at: 1 + 31 put: $o asciiValue.
	ScanCode at: 1 + 32 put: $u asciiValue.
	ScanCode at: 1 + 34 put: $i asciiValue.
	ScanCode at: 1 + 35 put: $p asciiValue.
	ScanCode at: 1 + 36 put: Character cr asciiValue.
	ScanCode at: 1 + 37 put: $l asciiValue.
	ScanCode at: 1 + 38 put: $j asciiValue.
	ScanCode at: 1 + 40 put: $k asciiValue.
	ScanCode at: 1 + 45 put: $n asciiValue.
	ScanCode at: 1 + 46 put: $m asciiValue.
	ScanCode at: 1 + 49 put: Character space asciiValue.
	ScanCode at: 1 + 123 put: 28.
	ScanCode at: 1 + 124 put: 29.
	ScanCode at: 1 + 125 put: 31.
	ScanCode at: 1 + 126 put: 30.
